"""
orna_guides.py
================
Manifest + reader for the per-class/build/topic community guides
(orna_guide_<topic>.txt, generated by orna_scrape_guides.py - see that
script's docstring for sources). Deliberately NOT the same shape as
orna_knowledge.py: that module holds ONE flattened multi-section corpus,
fuzzy-searched as a single blob, because its content is short community-
wiki FACTS (tier/HP/resistance rows) where a matching line or two is a
complete answer. These guides are long-form REASONING - why a build
works, tradeoffs between two setups - where grepping a fragment out
would lose the argument around it, so the right unit to hand the model
is "the whole guide for the class this question is about", selected by
name, not searched piecemeal. That's what resolve_guide/read_guide are
for; the ReAct loop's own class_guide tool (telegram_orna.py) is the
only caller.
"""
from __future__ import annotations

import difflib
from pathlib import Path
from typing import Optional

GUIDES = {
    "summoner": {
        "title": "Summoner - Ultimate Circle of Grand Summoners RESUMMONED",
        "path": "orna_guide_summoner.txt",
        "aliases": ["summoner", "grand summoner", "summoners"],
    },
    "thief": {
        "title": "Realmshifter/Thief raiding guide",
        "path": "orna_guide_thief.txt",
        "aliases": ["thief", "realmshifter", "rs", "corvus"],
    },
    "deity": {
        "title": "Deity - Getting started with Deity",
        "path": "orna_guide_deity.txt",
        "aliases": ["deity"],
    },
    "gilgamesh": {
        "title": "Gilgamesh - All Gilga Ward Pieces",
        "path": "orna_guide_gilgamesh.txt",
        "aliases": ["gilgamesh", "gilga", "gilga ward"],
    },
    "beowulf": {
        "title": "Beowulf - The Ultimate Guide",
        "path": "orna_guide_beowulf.txt",
        "aliases": ["beowulf", "beo", "beoa", "beoh", "valhallan"],
    },
    "swash": {
        "title": "Swash/Blade build gear guide (a build usable by any class, not a class itself)",
        "path": "orna_guide_swash.txt",
        "aliases": ["swash", "swashbuckler", "blade"],
    },
    "heretic": {
        "title": "Heretic - One Turn Orna",
        "path": "orna_guide_heretic.txt",
        "aliases": ["heretic"],
    },
    "towers": {
        "title": "Towers of Olympia Breakdown (gear/rewards/mechanics reference - "
                  "NOT the wild-tower floor-height algorithm, see orna_towers.py for that)",
        "path": "orna_guide_towers.txt",
        "aliases": ["tower", "towers", "tower of olympia", "towers of olympia", "wild tower", "wild towers"],
    },
}


def list_guides() -> list:
    """(topic_key, title) pairs, for the /orna system prompt to advertise
    what's available - derived from GUIDES itself so the prompt can't
    silently drift out of sync with what's actually on disk."""
    return [(key, g["title"]) for key, g in GUIDES.items()]


def resolve_guide(name: str) -> Optional[str]:
    """Resolve a free-text class/build/topic name to a GUIDES key -
    exact/substring match against the key and its aliases first, then a
    difflib fallback for typos (same two-step pattern orna_knowledge.py's
    _fuzzy_correct and orna_aussies.py's _resolve_stat_field already use
    elsewhere in this repo). None if nothing reasonably matches."""
    needle = name.strip().lower()
    if not needle:
        return None

    for key, g in GUIDES.items():
        if needle == key or needle in [a.lower() for a in g["aliases"]]:
            return key

    for key, g in GUIDES.items():
        candidates = [key] + g["aliases"]
        if any(needle in c or c in needle for c in (c.lower() for c in candidates)):
            return key

    alias_to_key = {a.lower(): key for key, g in GUIDES.items() for a in [key] + g["aliases"]}
    close = difflib.get_close_matches(needle, alias_to_key.keys(), n=1, cutoff=0.75)
    return alias_to_key[close[0]] if close else None


def read_guide(topic_key: str) -> Optional[str]:
    """Full raw file content for an already-resolved topic_key - no
    truncation here, that's the caller's job (how much context budget to
    spend is a loop-level decision, not this reader's)."""
    g = GUIDES.get(topic_key)
    if g is None:
        return None
    path = Path(__file__).with_name(g["path"])
    if not path.exists():
        return None
    return path.read_text(encoding="utf-8")


def _demo() -> None:
    """Run via `python3 orna_guides.py`."""
    assert resolve_guide("thief") == "thief"
    assert resolve_guide("realmshifter") == "thief"
    assert resolve_guide("Realmshifter raiding") == "thief"
    assert resolve_guide("swashbuckler") == "swash"
    assert resolve_guide("towers of olympia") == "towers"
    assert resolve_guide("gilga") == "gilgamesh"
    assert resolve_guide("nonexistent-class-xyz-123") is None
    assert resolve_guide("") is None

    for key in GUIDES:
        content = read_guide(key)
        assert content, f"{key}: expected non-empty guide content"
        assert len(content) > 500, f"{key}: suspiciously short ({len(content)} chars)"

    print(f"orna_guides._demo: all checks passed ({len(GUIDES)} guides)")


if __name__ == "__main__":
    _demo()
