"""
orna_knowledge.py
==================
Runtime reader for orna_knowledge.txt (generated by orna_scrape_knowledge.py)
- curated community reference data playorna.com's own codex doesn't track
at all (see that script's docstring for why - most notably per-monster/
boss elemental damage resistances/immunities, verified missing from the
live codex for a real reported case). Loaded once at import, searched
with plain substring matching: the data is a flattened, semi-structured
text blob by design, not typed tables (these are human-maintained wiki
sheets, not clean data), so a grep-shaped search is the right tool - same
"tool retrieves, model interprets" split as orna_calendar.py's events and
telegram_go.py's web search.
"""
from __future__ import annotations

import difflib
import re
from pathlib import Path
from typing import NamedTuple, Optional

DATA_PATH = Path(__file__).with_name("orna_knowledge.txt")
_WORD_RE = re.compile(r"[A-Za-z][A-Za-z'-]{2,}")


class Section(NamedTuple):
    title: str
    header: str  # best-guess column-label line for this section, "" if none found
    lines: list


_sections: Optional[list] = None
_word_vocab: Optional[set] = None


def _looks_like_header(line: str) -> bool:
    """A row of short " | "-separated tokens (e.g. "Item | Tier | Type |
    Exp | Orns") is very likely a column-label row; a row with few, long,
    sentence-like segments is prose. Good enough heuristic for these
    sheets - verified directly against several sections."""
    parts = line.split(" | ")
    if len(parts) < 3:
        return False
    return sum(len(p) for p in parts) / len(parts) <= 15


def _load() -> list:
    global _sections
    if _sections is not None:
        return _sections
    text = DATA_PATH.read_text(encoding="utf-8")
    sections = []
    for chunk in text.split("\n=== ")[1:]:  # [0] is the file's own leading comment header
        title_line, _, rest = chunk.partition("\n")
        title = title_line[:-4] if title_line.endswith(" ===") else title_line
        lines = [l for l in rest.split("\n") if l.strip()]
        header = next((l for l in lines[:20] if _looks_like_header(l)), "")
        sections.append(Section(title=title, header=header, lines=lines))
    _sections = sections
    return sections


def list_sections() -> list:
    """Section titles, for the /orna system prompt to advertise what this
    covers - derived from the data itself rather than a second hardcoded
    list that could drift out of sync with it."""
    return [s.title for s in _load()]


def _vocab() -> set:
    """Every distinct capitalized-ish word appearing anywhere in the
    knowledge base, for fuzzy query correction (see search())."""
    global _word_vocab
    if _word_vocab is None:
        vocab = set()
        for sec in _load():
            for line in sec.lines:
                vocab.update(_WORD_RE.findall(line))
        _word_vocab = vocab
    return _word_vocab


def _fuzzy_correct(query: str) -> Optional[str]:
    """A transliterated name (e.g. "Sirius" from Ukrainian "Сіріус") often
    doesn't exactly match the game's actual spelling ("Sirus") - the same
    problem search_codex's own retries exist for, and the same fix
    already used elsewhere in this codebase (orna_aussies.
    _resolve_stat_field/_resolve_attr_field): fuzzy-match each word
    against the corpus's real vocabulary and substitute the close match.
    Returns None if nothing changed (caller then knows not to re-search)."""
    vocab = _vocab()
    # Match case-INSENSITIVELY, as the docstring's cited sibling
    # (_resolve_stat_field) does: difflib.SequenceMatcher is case-sensitive,
    # so a lowercase query word ("sirius") vs a capitalized corpus word
    # ("Sirus") scores 0.727 (below the 0.75 cutoff) and silently fails to
    # correct - the exact transliteration case this function exists for.
    # Lowercase both for scoring (0.909, passes), then substitute the real
    # original-case corpus spelling.
    lower_to_orig: dict = {}
    for v in vocab:
        lower_to_orig.setdefault(v.lower(), v)
    lower_vocab = list(lower_to_orig)
    words = query.split()
    corrected = []
    changed = False
    for w in words:
        wl = w.lower()
        if wl in lower_to_orig:
            corrected.append(w)
            continue
        close = difflib.get_close_matches(wl, lower_vocab, n=1, cutoff=0.75)
        if close:
            corrected.append(lower_to_orig[close[0]])
            changed = True
        else:
            corrected.append(w)
    return " ".join(corrected) if changed else None


def _search_once(needle: str, section: str, limit: int) -> str:
    out = []
    matched_total = 0
    for sec in _load():
        if section and section.strip().lower() not in sec.title.lower():
            continue
        hits = [l for l in sec.lines if needle in l.lower()]
        if not hits:
            continue
        shown = hits[:max(1, limit - matched_total)]
        block = [f"[{sec.title}]"]
        if sec.header and sec.header not in shown:
            block.append(sec.header)
        block.extend(shown)
        out.append("\n".join(block))
        matched_total += len(shown)
        if matched_total >= limit:
            break
    return "\n\n".join(out)


def search(query: str, section: str = "", limit: int = 20) -> str:
    """Case-insensitive substring search across the knowledge base.
    `section` narrows to sections whose title contains it (case-
    insensitive substring, e.g. "monster" -> "Monster Data (...)");
    leave empty to search every section. Returns matching lines grouped
    by section, each group prefixed with that section's best-guess header
    line (once) so a bare data row like "0 | 0 | 0" isn't meaningless on
    its own - capped to `limit` matched lines total. On an exact-substring
    miss, retries once with each query word fuzzy-corrected against the
    corpus's own vocabulary (see _fuzzy_correct) before giving up. Empty
    string if nothing matched anywhere (caller decides how to report that)."""
    query = query.strip()
    if not query:
        return ""
    result = _search_once(query.lower(), section, limit)
    if result:
        return result
    corrected = _fuzzy_correct(query)
    if corrected:
        result = _search_once(corrected.lower(), section, limit)
    return result
