"""
orna_knowledge.py
==================
Runtime reader for orna_knowledge.txt (generated by orna_scrape_knowledge.py)
- curated community reference data playorna.com's own codex doesn't track
at all (see that script's docstring for why - most notably per-monster/
boss elemental damage resistances/immunities, verified missing from the
live codex for a real reported case). Loaded once at import, searched
with plain substring matching: the data is a flattened, semi-structured
text blob by design, not typed tables (these are human-maintained wiki
sheets, not clean data), so a grep-shaped search is the right tool - same
"tool retrieves, model interprets" split as orna_calendar.py's events and
telegram_go.py's web search.
"""
from __future__ import annotations

import difflib
import logging
import re
import time
from pathlib import Path
from typing import NamedTuple, Optional

logger = logging.getLogger(__name__)

DATA_PATH = Path(__file__).with_name("orna_knowledge.txt")
# The sheets behind this corpus are hand-maintained by the community and DO
# change, so the committed .txt goes stale between manual scraper runs. Same
# treatment as orna_aussies/orna_releases: refresh into a gitignored cache on
# a 1-week TTL. The committed file stays as the FALLBACK - if Google is
# unreachable or a sheet was deleted, we serve the last good copy instead of
# losing the knowledge base entirely, which is strictly better than what a
# fetch-only design would do.
CACHE_DIR = Path(__file__).parent / ".knowledge_cache"
CACHE_FILE = "orna_knowledge.txt"
CACHE_TTL_SECONDS = 7 * 24 * 3600
_WORD_RE = re.compile(r"[A-Za-z][A-Za-z'-]{2,}")


class Section(NamedTuple):
    title: str
    header: str  # best-guess column-label line for this section, "" if none found
    lines: list


_sections: Optional[list] = None
_word_vocab: Optional[set] = None


def _looks_like_header(line: str) -> bool:
    """A row of short " | "-separated tokens (e.g. "Item | Tier | Type |
    Exp | Orns") is very likely a column-label row; a row with few, long,
    sentence-like segments is prose. Good enough heuristic for these
    sheets - verified directly against several sections."""
    parts = line.split(" | ")
    if len(parts) < 3:
        return False
    # The FIRST segment may not be a sentence. Live bug 2026-09-24: the
    # "Gear XP/Orn/Gold Boosts" section's real header is "Item | Tier | Type
    # | Exp | Orns | Gold | Luck | ...", but the line above it is "All values
    # are multiplicators and stack with each other | 0.1 | 1 | 1 | 1.1 |
    # ...", whose 9-word first segment is dragged under the average by the
    # ten bare numbers after it. That prose line won, so every answer built
    # on this table had UNLABELLED columns and the model guessed which one
    # was Orns - live, two runs of one request read the same rows as 1.2 and
    # as 2 for Temple of Wealth (Orns is 1.2; the 2 it grabbed isn't in that
    # row at all) and as 1.2 and 1.1 for Vulcan's Brew (1.2), landing on
    # totals of x195.81 and x299.16 for the same question.
    # Testing the first segment specifically, rather than every segment or a
    # character cap: a header's first cell is the row-label column's NAME
    # ("Item", "Type", "Members", "Tier & Rarity") and is never a sentence,
    # while a prose line-in puts its sentence exactly there. Both stricter
    # rules also rejected the Proofs section's genuine header, which carries
    # a stray spreadsheet note ("Price Formulae, for those interested:") in
    # its LAST cell and whose emoji labels ("👺 Anguish") are long in len()
    # terms while still being ordinary two-word labels.
    if len(parts[0].split()) > 4:
        return False
    return sum(len(p) for p in parts) / len(parts) <= 15


def _corpus_stats(text: str) -> dict:
    """{section title: non-empty line count} - what _sane_rebuild compares.
    PER SECTION on purpose: a whole-corpus line count is far too coarse, and
    the realistic failure is one tab coming back empty while the other 15 are
    fine. Emptying the largest tab only costs ~9% of the total lines, which a
    whole-corpus ratio check waves straight through (measured)."""
    out = {}
    for chunk in text.split("\n=== ")[1:]:
        title, _, rest = chunk.partition("\n")
        out[title] = sum(1 for l in rest.split("\n") if l.strip())
    return out


# A section may keep this fraction of its committed lines and still pass.
# Google returning HTTP 200 with a truncated or empty CSV is the failure this
# guards: without it, one bad fetch is cached for a WEEK and silently answers
# from a corpus missing a whole tab - exactly the quiet staleness the refresh
# exists to prevent. Halving is generous for ordinary community edits, which
# add and remove a few rows at a time.
_MIN_SECTION_RATIO = 0.5
# Sections this small are noise-prone (a 4-line tab losing 2 rows is not a
# fetch failure), so they are only checked for existing at all.
_SMALL_SECTION_LINES = 8


def _sane_rebuild(text: str, fallback: str) -> bool:
    """Whether a freshly-built corpus looks complete next to the committed
    copy. A rejected rebuild is never cached, so the bot keeps serving the
    last good data and the failure is visible in the log.

    If the sheets ever legitimately shrink past this, the rebuild keeps being
    rejected until someone re-runs orna_scrape_knowledge.py and commits - at
    which point the fallback becomes the new baseline and it passes again.
    That is deliberate: a human confirming a big shrink is right beats the
    bot silently accepting one."""
    new, old = _corpus_stats(text), _corpus_stats(fallback)
    for title, old_lines in old.items():
        if title not in new:
            logger.warning("orna_knowledge: rebuild is missing section %r - rejecting", title[:60])
            return False
        if old_lines > _SMALL_SECTION_LINES and new[title] < old_lines * _MIN_SECTION_RATIO:
            logger.warning("orna_knowledge: section %r came back with %d lines, committed copy has %d - rejecting",
                           title[:60], new[title], old_lines)
            return False
    return True


def _corpus_text() -> str:
    """The knowledge corpus, refreshed from the source sheets at most weekly.

    Order: a fresh cache, else a rebuild from the sheets, else whatever we
    have on disk (a stale cache first, since it is newer than the committed
    file, then the committed file). Every fetch failure is a warning, never
    an exception - a Google outage must not take the knowledge base down.

    Blocking: a rebuild is ~16 HTTP requests. Every caller of search()
    already goes through asyncio.to_thread (see
    telegram_orna._run_knowledge_tool), which is what keeps that off the
    event loop."""
    cached = CACHE_DIR / CACHE_FILE
    if cached.exists() and time.time() - cached.stat().st_mtime < CACHE_TTL_SECONDS:
        try:
            return cached.read_text(encoding="utf-8")
        except OSError:
            logger.warning("orna_knowledge: cache unreadable, rebuilding")

    try:
        from orna_scrape_knowledge import build_text
        text = build_text()
        # Compare against the committed copy rather than a bare "looks
        # non-empty" check: a partial fetch can still produce every section
        # header with most of the rows missing.
        if not _sane_rebuild(text, DATA_PATH.read_text(encoding="utf-8")):
            raise ValueError("rebuilt corpus looks incomplete next to the committed copy")
        CACHE_DIR.mkdir(exist_ok=True)
        tmp = cached.with_suffix(cached.suffix + ".tmp")
        tmp.write_text(text, encoding="utf-8")
        tmp.replace(cached)  # atomic, so a crash mid-write can't leave a torn cache
        logger.info("orna_knowledge: refreshed corpus from source sheets (%d bytes)", len(text))
        return text
    except Exception:
        logger.warning("orna_knowledge: refresh failed, serving the copy on disk", exc_info=True)

    if cached.exists():
        try:
            return cached.read_text(encoding="utf-8")  # stale, but newer than the committed file
        except OSError:
            pass
    return DATA_PATH.read_text(encoding="utf-8")


def refresh_cache() -> None:
    """Force a rebuild from the sheets next time the corpus is needed."""
    global _sections, _word_vocab
    _sections = _word_vocab = None
    (CACHE_DIR / CACHE_FILE).unlink(missing_ok=True)


def refetch_now() -> dict:
    """Rebuild from the sheets right now, ignoring the TTL; small stats for a
    confirmation reply (see /update_codex)."""
    refresh_cache()
    sections = _load()
    return {"sections": len(sections), "lines": sum(len(s.lines) for s in sections)}


def _load() -> list:
    global _sections
    if _sections is not None:
        return _sections
    text = _corpus_text()
    sections = []
    for chunk in text.split("\n=== ")[1:]:  # [0] is the file's own leading comment header
        title_line, _, rest = chunk.partition("\n")
        title = title_line[:-4] if title_line.endswith(" ===") else title_line
        lines = [l for l in rest.split("\n") if l.strip()]
        header = next((l for l in lines[:20] if _looks_like_header(l)), "")
        sections.append(Section(title=title, header=header, lines=lines))
    _sections = sections
    return sections


def list_sections() -> list:
    """Section titles, for the /orna system prompt to advertise what this
    covers - derived from the data itself rather than a second hardcoded
    list that could drift out of sync with it."""
    return [s.title for s in _load()]


def _vocab() -> set:
    """Every distinct capitalized-ish word appearing anywhere in the
    knowledge base, for fuzzy query correction (see search())."""
    global _word_vocab
    if _word_vocab is None:
        vocab = set()
        for sec in _load():
            for line in sec.lines:
                vocab.update(_WORD_RE.findall(line))
        _word_vocab = vocab
    return _word_vocab


def _fuzzy_correct(query: str) -> Optional[str]:
    """A transliterated name (e.g. "Sirius" from Ukrainian "Сіріус") often
    doesn't exactly match the game's actual spelling ("Sirus") - the same
    problem search_codex's own retries exist for, and the same fix
    already used elsewhere in this codebase (orna_aussies.
    _resolve_stat_field/_resolve_attr_field): fuzzy-match each word
    against the corpus's real vocabulary and substitute the close match.
    Returns None if nothing changed (caller then knows not to re-search)."""
    vocab = _vocab()
    # Match case-INSENSITIVELY, as the docstring's cited sibling
    # (_resolve_stat_field) does: difflib.SequenceMatcher is case-sensitive,
    # so a lowercase query word ("sirius") vs a capitalized corpus word
    # ("Sirus") scores 0.727 (below the 0.75 cutoff) and silently fails to
    # correct - the exact transliteration case this function exists for.
    # Lowercase both for scoring (0.909, passes), then substitute the real
    # original-case corpus spelling.
    lower_to_orig: dict = {}
    for v in vocab:
        lower_to_orig.setdefault(v.lower(), v)
    lower_vocab = list(lower_to_orig)
    words = query.split()
    corrected = []
    changed = False
    for w in words:
        wl = w.lower()
        if wl in lower_to_orig:
            corrected.append(w)
            continue
        close = difflib.get_close_matches(wl, lower_vocab, n=1, cutoff=0.75)
        if close:
            corrected.append(lower_to_orig[close[0]])
            changed = True
        else:
            corrected.append(w)
    return " ".join(corrected) if changed else None


def _block(sec, shown: list) -> str:
    """One section's result block: title, its column header (once), rows."""
    block = [f"[{sec.title}]"]
    if sec.header and sec.header not in shown:
        block.append(sec.header)
    block.extend(shown)
    return "\n".join(block)


def _search_once(needle: str, section: str, limit: int) -> str:
    out = []
    matched_total = 0
    for sec in _load():
        if section and section.strip().lower() not in sec.title.lower():
            continue
        hits = [l for l in sec.lines if needle in l.lower()]
        if not hits:
            continue
        shown = hits[:max(1, limit - matched_total)]
        out.append(_block(sec, shown))
        matched_total += len(shown)
        if matched_total >= limit:
            break
    return "\n\n".join(out)


def _search_words(needle: str, section: str, limit: int) -> str:
    """Rank lines by how many DISTINCT query words they contain, for a query
    that names SEVERAL things at once.

    _search_once needs the whole query as one substring, so a combined query
    can only match a line containing every subject - i.e. nothing. Live bug
    2026-09-24: knowledge_search("Shrine of Luck Lucky Silver Coin Temple of
    Wealth Volcan's Brew") returned empty, the loop was told "not in the
    knowledge base", and it invented the multipliers instead (two runs of one
    request answered x195.81 and x305.80 for the same question). An earlier
    fix split the query on ","/"and"/"та", which worked until the model wrote
    the same list space-separated with no delimiter at all - hence scoring
    words, which needs no delimiter and covers both.

    Words shorter than 3 chars are dropped so "of"/"a" can't match every row.
    A line needs >= 2 distinct query words to count, which is what keeps a
    single shared word from dragging in the whole corpus."""
    words = {w for w in _WORD_RE.findall(needle.lower()) if len(w) >= 3}
    if len(words) < 2:
        return ""
    scored = []
    for order, sec in enumerate(_load()):
        if section and section.strip().lower() not in sec.title.lower():
            continue
        for line in sec.lines:
            low = line.lower()
            score = sum(1 for w in words if w in low)
            if score >= 2:
                scored.append((score, order, sec, line))
    if not scored:
        return ""
    scored.sort(key=lambda t: -t[0])
    keep = scored[:limit]
    out, seen = [], {}
    for _, order, sec, line in sorted(keep, key=lambda t: t[1]):
        seen.setdefault(id(sec), (sec, []))[1].append(line)
    for sec, lines in seen.values():
        out.append(_block(sec, lines))
    return "\n\n".join(out)


_SECTION_URLS: Optional[dict] = None


def source_url(section_title: str) -> Optional[str]:
    """The Google Sheet + tab a section was scraped from, for citing it back
    to the user - or None if the title isn't one we generated.

    Built from orna_scrape_knowledge._TABLES, which is where the ids already
    live, rather than a second copy here that could drift. That module is a
    one-off script but importing it is side-effect free (its work is behind
    `if __name__ == "__main__"`). The key is the section title exactly as the
    generated file writes it - "<title> (<source note>)" - so this matches
    Section.title without any extra parsing."""
    global _SECTION_URLS
    if _SECTION_URLS is None:
        try:
            from orna_scrape_knowledge import _TABLES
            _SECTION_URLS = {
                f"{title} ({source})": f"https://docs.google.com/spreadsheets/d/{doc}/edit#gid={gid}"
                for title, doc, gid, source in _TABLES
            }
        except Exception:  # the scraper is optional at runtime - degrade to "no link"
            logger.warning("orna_knowledge: could not load source URLs", exc_info=True)
            _SECTION_URLS = {}
    return _SECTION_URLS.get(section_title)


def search(query: str, section: str = "", limit: int = 20) -> str:
    """Case-insensitive substring search across the knowledge base.
    `section` narrows to sections whose title contains it (case-
    insensitive substring, e.g. "monster" -> "Monster Data (...)");
    leave empty to search every section. Returns matching lines grouped
    by section, each group prefixed with that section's best-guess header
    line (once) so a bare data row like "0 | 0 | 0" isn't meaningless on
    its own - capped to `limit` matched lines total. On an exact-substring
    miss, retries once with each query word fuzzy-corrected against the
    corpus's own vocabulary (see _fuzzy_correct) before giving up. Empty
    string if nothing matched anywhere (caller decides how to report that)."""
    query = query.strip()
    if not query:
        return ""
    result = _search_once(query.lower(), section, limit)
    if result:
        return result
    corrected = _fuzzy_correct(query)
    if corrected:
        result = _search_once(corrected.lower(), section, limit)
        if result:
            return result
    # Last resort: score by shared words, for a query naming several things
    # at once (no single line can contain all of them). See _search_words.
    return _search_words(corrected or query, section, limit)


def _demo() -> None:
    """Pins _looks_like_header against the two lines that actually fight
    over the "Gear XP/Orn/Gold Boosts" section (see that function), plus
    the Proofs header a stricter rule kept rejecting. Run:
    `python3 orna_knowledge.py`."""
    real = "Item | Tier | Type | Exp | Orns | Gold | Luck | Spawn | View | BASE | Broken"
    prose = "All values are multiplicators and stack with each other | 0.1 | 1 | 1 | 1.1 | 1.15"
    assert _looks_like_header(real), "real column header must be recognised"
    assert not _looks_like_header(prose), "prose line-in must NOT win the header slot"
    assert not _looks_like_header("Some prose without any pipes at all")

    # The Proofs section's real header is the case a stricter rule kept
    # rejecting (emoji labels, plus a stray sheet note in its LAST cell) -
    # assert against the live line rather than an abbreviated copy, whose
    # different segment count changes the average-length test.
    proofs = next(s for s in _load() if s.title.startswith("Proofs"))
    assert proofs.header.startswith("Tier & Rarity | Material |"), proofs.header[:80]

    # Every section must resolve to a header whose first cell is a label.
    for sec in _load():
        if sec.header:
            assert len(sec.header.split(" | ")[0].split()) <= 4, (sec.title, sec.header[:60])

    # The live regression: Orns is a NAMED column now, not the 5th unlabelled one.
    hit = search("Temple of Wealth", limit=3)
    assert "| Orns |" in hit, hit
    assert "Temple of Wealth | - | Kingdom Research | - | 1.2" in hit, hit

    # A truncated rebuild must be rejected, not cached for a week.
    full = DATA_PATH.read_text(encoding="utf-8")
    assert _sane_rebuild(full, full), "an identical rebuild must pass"
    parts = full.split("\n=== ")
    # the realistic failure: every header present, ONE tab came back empty.
    # A whole-corpus ratio check passes this (it is ~9% of the lines), which
    # is exactly why the comparison is per section.
    biggest = max(range(1, len(parts)), key=lambda i: len(parts[i]))
    emptied = list(parts)
    emptied[biggest] = emptied[biggest].split("\n")[0] + "\n"
    one_tab_gone = parts[0] + "".join("\n=== " + p for p in emptied[1:])
    assert not _sane_rebuild(one_tab_gone, full), "an empty tab must be rejected"
    # a section vanishing entirely
    assert not _sane_rebuild(parts[0] + "".join("\n=== " + p for p in parts[2:]), full)
    # ...while an ordinary edit (a few rows removed) must still pass
    trimmed = list(parts)
    trimmed[biggest] = "\n".join(trimmed[biggest].split("\n")[:-3])
    assert _sane_rebuild(parts[0] + "".join("\n=== " + p for p in trimmed[1:]), full), \
        "a few removed rows is a normal edit, not a failed fetch"

    # A multi-subject query must find every subject, with NO delimiter to
    # split on, and across a spelling the corpus doesn't use ("Volcan's" ->
    # "Vulcan's"). This returned "" before _search_words existed.
    multi = search("Shrine of Luck Lucky Silver Coin Temple of Wealth Volcan's Brew", limit=8)
    for row in ("Lucky Silver Coin | 4", "Vulcan's Brew | 6", "Shrine of Luck | -", "Temple of Wealth | -"):
        assert row in multi, (row, multi[:300])
    assert "| Orns |" in multi, multi[:300]
    # ...and a single-subject query must still take the exact-substring path.
    assert "Knight Sirus" in search("Knight Sirus", limit=3)
    print("orna_knowledge: all checks passed")


if __name__ == "__main__":
    _demo()
